// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Album struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	ImgUrl string `json:"img_url"`
	UserID int64  `json:"user_id"`
}

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID       int64          `json:"id"`
	Username string         `json:"username"`
	Password string         `json:"password"`
	Fullname string         `json:"fullname"`
	Email    sql.NullString `json:"email"`
	Gender   int32          `json:"gender"`
	RoleID   int32          `json:"role_id"`
	Describe string         `json:"describe"`
	Avt      string         `json:"avt"`
	CreateAt time.Time      `json:"create_at"`
}
